### ISSUE TITLE
新的请求需要token

### ISSUE THREAD

**Issue by sk8heidong** [ReaJason/17wanxiaoCheckin-Actions#10]
![Screenshot_20201023_001336](https://user-images.githubusercontent.com/54124974/96900391-9cb22c00-14c4-11eb-8341-22f941248c1b.jpg)
token是有时效的，没研究出来怎么获取~

**Comment by srcrs** [comment]
> ![Screenshot_20201023_001336](https://user-images.githubusercontent.com/54124974/96900391-9cb22c00-14c4-11eb-8341-22f941248c1b.jpg)
> token是有时效的，没研究出来怎么获取~

参考一下这个项目 https://github.com/zhongbr/wanmei_campus 模拟登录完美校园的，能拿到token

**Comment by ReaJason** [comment]
已更新token的获取
