### ISSUE TITLE
http://reajason.top网站无法登录

### ISSUE THREAD

**Issue by 24182400966** [ReaJason/17wanxiaoCheckin-Actions#11]
就是想问一下大佬，完美校园开启了vnp无法抓包，最后您是怎么解决这个问题的

**Comment by ReaJason** [comment]
可以试试安卓5.1模拟器+xp框架+jsuttustme模块+fiddle来抓包。这个健康打卡抓包的话，请在数据填写好之后，最后准备提交打卡的时候再开启抓包就可以抓到了，如果你提前开启抓包会被拦住。
我这个网站目前就挂载在github.io上，可以尝试更换网络环境访问哦，比如挂个VPN翻出来，我也没整服务器不知道有什么白嫖的方法部署到国内阿里云或者腾讯云上面。

**Comment by ReaJason** [comment]
你试试访问一下这个url

**Comment by ReaJason** [comment]
试试访问这个网站：[https://reajason.top/](https://reajason.top/)

**Comment by 24182400966** [comment]
大佬，可不可以发一下登录的请求api地址

**Comment by ReaJason** [comment]
完美校园模拟登陆请参考这个，别人已经写好了：[https://github.com/zhongbr/wanmei_campus](https://github.com/zhongbr/wanmei_campus)
