### ISSUE TITLE
请求token时，请求体里有什么？

### ISSUE THREAD

**Issue by llkhs** [ReaJason/17wanxiaoCheckin-Actions#13]
我抓包发现请求体是有我自己的token参数，才返回true，您的脚本里面有post一下token吗，还是设定变量.

**Comment by ReaJason** [comment]
你是在抓包token如何获取吗？可以直接拿别人已经写好的 [https://github.com/zhongbr/wanmei_campus](https://github.com/zhongbr/wanmei_campus) 代码进行参考，获取token需要逆向分析app的

**Comment by llkhs** [comment]
是的！

 「# 如果不请求一下这个地址，token就会失效」
我通过抓包发现，我这边跟你那的请求token地址不一样，我不太确定所以开issue
![3DF3D27E-8000-478F-A172-A2C06487F5F4](https://user-images.githubusercontent.com/51050409/100135701-f7c0af80-2ec4-11eb-953d-a43f44645134.jpeg)

**Comment by ReaJason** [comment]
完美校园的api制作就是这个样子的，用同一个url，发送的参数不同，返回的值不同。你也可以把我的替换成你的，如果没有运行出错的话，不必担心，能使用就行。

**Comment by llkhs** [comment]
替换前与替换后的运行结果
![Uploading 865BD483-1C7F-47C4-A784-3BC6003BCF09.png…]()

**Comment by llkhs** [comment]
![822BB2BF-96F2-42CC-8144-C9888F3FE68D](https://user-images.githubusercontent.com/51050409/100179900-ea7de200-2f11-11eb-895e-55a5694611f5.png)

> 替换前后的运行结果，没有返回参数，failure了，我继续排查问题

**Comment by ReaJason** [comment]
我的代码可以用的话，我建议你花时间去学新的知识更好。
