### ISSUE TITLE
内蒙古工业大学测试通过

### ISSUE THREAD

**Issue by LMDHCN** [ReaJason/17wanxiaoCheckin-Actions#15]
不过我们还得校内打卡（悲），等等去试试把两个项目整合在一起

**Comment by ReaJason** [comment]
可以在手机上设置定位在校内打一次卡，如果不在校内可以关掉定位，自己输入地址，进行打卡，打完卡，再次进入应该会自动刷新出上次打卡的信息，这样这个项目应该就可以打在你们学校了

**Comment by 126wang** [comment]
> 可以在手机上设置定位在校内打一次卡，如果不在校内可以关掉定位，自己输入地址，进行打卡，打完卡，再次进入应该会自动刷新出上次打卡的信息，这样这个项目应该就可以打在你们学校了

内工大这个是两个选项，Github是打卡第一个“校外打卡”而不是“校内打卡”

**Comment by ReaJason** [comment]
你可以修改代码的，在get_post_json函数中打印获取完美校园post参数成功的上面，遍历post_dict['updatainfo']，然后判断你那个字段的名字，把value改为校内打卡，就根据你微信推送的json字段来改就好了。

**Comment by ReaJason** [comment]
不知道怎么实现的话，可以截一下你json字段updateinfo那一段给我，我把代码写给你加上去

**Comment by 126wang** [comment]
抓包里边的代码么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午3:00
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"海中之龙"<1262818842@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 内蒙古工业大学测试通过 (#15)



 不知道怎么实现的话，可以截一下你json字段updateinfo那一段给我，我把代码写给你加上去

**Comment by ReaJason** [comment]
微信推送我设置推送了json字段，就那个

**Comment by CY-Jan26** [comment]
校内打卡是怎么弄得，我只能健康打卡

**Comment by ReaJason** [comment]
啊啊啊，我理解错了，这个健康打卡能去用就好🤗

**Comment by CY-Jan26** [comment]
进来有两个选项，一个是健康打卡，一个是校内打卡
我们要求用那个校内的，该怎么实现的

**Comment by ReaJason** [comment]
你可以根据我的抓包教程，抓下校内打卡签到包，按道理校内打卡的包大差不差的，我们没有这个选项没研究过。

**Comment by 126wang** [comment]
我抓到包了，但是不会用，哎…

**Comment by ReaJason** [comment]
方便提供下账号吗reajason@163.com，我也可以开发合并到这个项目中去

**Comment by CY-Jan26** [comment]
完美校园账号？？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午5:41
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 内蒙古工业大学测试通过 (#15)





 
方便提供下账号吗reajason@163.com，我也可以开发合并到这个项目中去

**Comment by ReaJason** [comment]
是的

**Comment by CY-Jan26** [comment]
为啥我用这个模拟器，打卡抓包一直是定位功能没打开无法定位，但是我把能打开定位服务都打开了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午5:48
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 内蒙古工业大学测试通过 (#15)





 
是的

**Comment by ReaJason** [comment]
我手机用虚拟定位不起作用，估计模拟器也做了检测了，还没找到解决办法

**Comment by CY-Jan26** [comment]
{"businessType":"epmpics","method":"submitUpInfoSchool","jsonData":{"deptStr":{"deptid":229028,"text":"理工学院-计算机科学与技术（专升本）-2020级1班"},"areaStr":"{\"streetNumber\":\"\",\"street\":\"大梁路辅路\",\"district\":\"龙亭区\",\"city\":\"开封市\",\"province\":\"河南省\",\"town\":\"\",\"pois\":\"河南天地药业股份有限公司-北门\",\"lng\":114.32716600000175,\"lat\":34.80734596586419,\"address\":\"龙亭区大梁路辅路河南天地药业股份有限公司-北门\",\"text\":\"河南省-开封市\",\"code\":\"\"}","reportdate":1606833617471,"customerid":743,"deptid":229028,"source":"app","templateid":"clockSign3","stuNo":"2003624031","username":"陈阳","userid":22689757,"updatainfo":[{"propertyname":"temperature","value":"36.6"},{"propertyname":"symptom","value":"无症状"}],"customerAppTypeRuleId":139,"clockState":0,"token":"6466c8d1-5a1f-4634-9e27-1cebf8dfb120"},"token":"6466c8d1-5a1f-4634-9e27-1cebf8dfb120"}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 

json字段能换成上面这个吗，咋换的？，这个是校内打卡抓的包，那个是健康打卡，参数都不一样





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 晚上11:09
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 内蒙古工业大学测试通过 (#15)





 
我手机用虚拟定位不起作用，估计模拟器也做了检测了，还没找到解决办法

**Comment by llkhs** [comment]
可以的，表单格式都差不多的，自己研究一下代码，再把参数改成自己的，你是计算机新生，动动手摸索一下这项目和研究一下你抓到的包，会学到很多知识，对你有好处！
