### ISSUE TITLE
1823，获取完美校园打卡post参数失败

### ISSUE THREAD

**Issue by mdalin99** [ReaJason/17wanxiaoCheckin-Actions#16]
1823，获取完美校园打卡post参数失败

**Comment by ReaJason** [comment]
可以试着在get_post_json函数中res=.......后面加入print(res.text)看，获取的是什么

**Comment by mdalin99** [comment]
{'msg': '业务异常', 'code': '10007', 'data': '无法找到该机构的投票模板数据!'}

**Comment by ReaJason** [comment]
啊这，你手机完美校园app打卡能自动填写吗，试了没，这个错误没遇到过

**Comment by mdalin99** [comment]
可以自动填写。。
我自己跟着步骤抓包发现找不到sass那些包..
谢谢大佬回复：）

**Comment by llkhs** [comment]
那就研究一下，哪些包的响应体与演示那边是差不多的，再改一下脚本。
