### ISSUE TITLE
有部分信息需要自己填写，其余信息是自动填写的，如何自动填写需要填写的信息。

### ISSUE THREAD

**Issue by zdbss** [ReaJason/17wanxiaoCheckin-Actions#18]
以下信息需要自己填写
21天内本人或家庭成员是否到过/途经/中转/停留中高风险地区（含天津地区、新疆喀什地区和境外）： None
今日体温（腋下体温） None
`{
                "propertyname": "isTransitArea",
                "value": null
            },
            {
                "propertyname": "temperature",
                "value": null
            },`

**Comment by zdbss** [comment]
体温数据固定值即可，如果可以随机正常体温更好。

**Comment by ReaJason** [comment]
在17wanxiao.py的get_post_json函数里面，这个地方添加如下代码：
```
# print(json.dumps(post_dict, sort_keys=True, indent=4, ensure_ascii=False))
# 在这里修改没有填写的数据，遍历post_dict['updatainfo']修改就行
for i in post_dict['updatainfo']:
    if i['propertyname'] == 'isTransitArea':
        i['value'] = '(这里设置你那个是否，你看你app打卡这里选项是哪个就填什么，一般就是无或者否)'
    if i['propertyname'] == 'temperature':
        i['value'] = '36.5'
logging.info('获取完美校园打卡post参数成功')
```

**Comment by ReaJason** [comment]
在17wanxiao.py的check_in函数里面，这个地方添加如下代码：

```
# 获取健康打卡的参数
json1 = {"businessType": "epmpics",
    "jsonData": {"templateid": "pneumonia", "token": token},
    "method": "userComeApp"}
post_dict = get_post_json(token, json1)
for i in post_dict['updatainfo']:
    if i['propertyname'] == 'isTransitArea':  # 字段名（其他请举一反三）
        i['value'] = '否'                     # 设置值
    if i['propertyname'] == 'temperature':
        i['value'] = '36.5'
if not post_dict:
    errmsg = '获取完美校园打卡post参数失败'
    logging.warning(errmsg)
    return False
```

**Comment by asayake777** [comment]
for i in post_dict['updatainfo']:
    if i['propertyname'] == 'wengdu':
        i['value'] = '0'
我添加了这些代码，报错
Process completed with exit code 1.
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
请问这是为什么呢

**Comment by ReaJason** [comment]
缩进不对，if还要缩到for里面去，注意看我README写的格式

**Comment by asayake777** [comment]
> 缩进不对，if还要缩到for里面去，注意看我README写的格式
ok了,谢谢😘
