### ISSUE TITLE
切记，代码可以跑，就不要重新fork，求代码安稳运行即可

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/17wanxiaoCheckin-Actions#19]
代码更新，请删除原fork仓库，重新fork一次该仓库
1.开启actions的时候，请务必查看下方的17WanxiaoCheckIn这个workflow是开启的状态，如果是感叹号请点进去Enable打开，否则修改了readme也触发不了actions
2.有问题在此issue下面回复

**Comment by CY-Jan26** [comment]
为啥我添加两个用户，一个打卡成功，另一个失败，显示 ‘请在正确的打卡时间打卡’

**Comment by ReaJason** [comment]
我获取校内打卡的顺序错了，以至于时间不对，现在应该好了，感谢反馈，请重新fork使用

**Comment by CY-Jan26** [comment]
增加多人打卡，是不是每次都要把新增的这个人重新抓一下包

因为都是一个学校的，可不可以固定一个学校的地址直接打卡？？具体在哪里修改？？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 中午11:47
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 更新请重新fork仓库 (#19)





 
我获取校内打卡的顺序错了，以至于时间不对，现在应该好了，感谢反馈，请重新fork使用

**Comment by ReaJason** [comment]
不用，只要健康打卡打过一次卡，就会自动获取上次打卡的信息来打卡

**Comment by ReaJason** [comment]
这上边打不了卡的话，可以手机登录一下完美校园打一次卡，这边再试

**Comment by CY-Jan26** [comment]
可以打了，这个有人数上线吗，最多多少，超过了该怎么弄？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午2:43
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 更新请重新fork仓库 (#19)





 
这上边打不了卡的话，可以手机登录一下完美校园打一次卡，这边再试

**Comment by ReaJason** [comment]
没有上限，要多少来多少，只是害怕中间信息输入错误

**Comment by JinKao** [comment]
时间对不上，我改成这样  
schedule:
    - cron: 20 21,22,3,4,9,10,11 * * *
今天下午推送的是时间是六点半和七点半，他这个追踪的是我的修改时间吗？？

**Comment by ReaJason** [comment]
第一个数字是20分钟，这个GitHub actions有几分钟延迟，差不多就到30分钟了，差不多是的

**Comment by JinKao** [comment]
嗯嗯这个是合适的，但是我需要的是凌晨0-7点打卡，然后中午12-13点30打卡，
我那个测试实在三点完成的，手机推送来的是18点半和19点半，也就是说可能是代码中“3,4”在起作用，您您看我这样分析的对吗？
“- cron: ”出来的是以手动修改最后一次的时间为0  时间往后计时
，，，，我感觉是这样的

**Comment by ReaJason** [comment]
20 22,4 * * *
这个就是早上6:20和12:20打卡，往后推个几分钟，差不多就是六点半是十二点半

你说的手机推送，可以看看运行记录，有时候会因为网络原因虽然这边打卡了但是会出现推送失败的情况，但是程序还是会根据你的计划时间运行

**Comment by ReaJason** [comment]
这个具体时间怎么来的，我README中Q&A第三个写了

**Comment by JinKao** [comment]
好的好的，感谢，我初学者，见谅~~！
，回头我再多看看
