### ISSUE TITLE
打卡包的问题

### ISSUE THREAD

**Issue by Taoshuaifei** [ReaJason/17wanxiaoCheckin-Actions#2]
我们打卡必须带token参数，登录的包又抓不到，有没有解决办法呀

**Comment by ReaJason** [comment]
我试过抓，抓登陆包模拟器可以抓到，不过token参数在APP内部已经实现封装了，逆向也看不出怎么来的，所以只能抓一个token参数，应该token参数可以一直用的，你们会有时效性吗，我们这直接提交数据，啥也不要都行

**Comment by Taoshuaifei** [comment]
我们token会过期，而且提交必须包含token，token过期的话返回登录失效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 中午12:43
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"↗一世◆繁华↖"<489402761@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 打卡包的问题 (#2)





 
我试过抓，抓登陆包模拟器可以抓到，不过token参数在APP内部已经实现封装了，逆向也看不出怎么来的，所以只能抓一个token参数，应该token参数可以一直用的，你们会有时效性吗，我们这直接提交数据，啥也不要都行

**Comment by ReaJason** [comment]
那属实难顶，只能乖乖打卡了
