### ISSUE TITLE
获取完美校园打卡Post参数失败

### ISSUE THREAD

**Issue by JackFengs** [ReaJason/17wanxiaoCheckin-Actions#21]
获取完美校园打卡Post参数失败
![报错](https://user-images.githubusercontent.com/18719644/101607533-a9bcb780-3a3f-11eb-9fe7-19b33c1bcc04.png)

**Comment by ReaJason** [comment]
这个可能你们完美校园打卡获取数据的接口不一样（猜测），（如果希望适配一下，可以邮箱发完美校园账号密码到首页的163邮箱号），可以自行 clone 到本地进行根据抓包教程抓包调试

**Comment by CY-Jan26** [comment]
今天怎么总是打卡出错，试了好几次，微信也不推送

**Comment by ReaJason** [comment]
> 今天怎么总是打卡出错，试了好几次，微信也不推送

这个应该是github服务器网络不稳定导致的，怕打卡失败，可以把cron写多一点的打卡次数

**Comment by CY-Jan26** [comment]
我把一天三打卡改成一天四次，刚才试了也没成功，是不是今天服务器问题大家都这样，明天再看看打卡情况？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReaJason/17wanxiaoCheckin-Actions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月12日(星期六) 下午2:21
收件人:&nbsp;"ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;;
抄送:&nbsp;"陈阳"<43511053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ReaJason/17wanxiaoCheckin-Actions] 获取完美校园打卡Post参数失败 (#21)





  
今天怎么总是打卡出错，试了好几次，微信也不推送
  
这个应该是github服务器网络不稳定导致的，怕打卡失败，可以把cron写多一点的打卡次数

**Comment by ReaJason** [comment]
> 获取完美校园打卡Post参数失败
> ![报错](https://user-images.githubusercontent.com/18719644/101607533-a9bcb780-3a3f-11eb-9fe7-19b33c1bcc04.png)

目前已初步适配，欢迎fork测试一下
