### ISSUE TITLE
设置的10点半打卡，结果10点20就自动打卡了

### ISSUE THREAD

**Issue by sw1128** [ReaJason/17wanxiaoCheckin-Actions#22]
为什么会出现这种情况

**Comment by ReaJason** [comment]
你贴一下你写的cron

**Comment by sw1128** [comment]
> 你贴一下你写的cron

![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
之前是20 2,4,8改成了05 4,8 刚刚12：05的时候也没打

**Comment by sw1128** [comment]
> 你贴一下你写的cron

去Actions手动re-run是可以成功的，就是这个设置的时间不知道哪儿出了问题

**Comment by ReaJason** [comment]
可以等明天这一时候再来看能不能运行，这个不知道，可能时间算到第二天了

**Comment by ReaJason** [comment]
> > 你贴一下你写的cron
> 
> ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打

突然想起来这个有时候不是准时的，会大概往后推10+分钟，我也不知道

**Comment by sw1128** [comment]
> > > 你贴一下你写的cron
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> 
> 突然想起来这个有时候不是准时的，会大概往后推10+分钟

今天12：05也没有打，cron还是05 4,8

**Comment by ReaJason** [comment]
> > > > 你贴一下你写的cron
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > 
> > 
> > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> 
> 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静

好家伙，刚有动静了

**Comment by sw1128** [comment]
> > > > > 你贴一下你写的cron
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > > 
> > > 
> > > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> > 
> > 
> > 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静
> 
> 好家伙，刚有动静了

刚刚是我手动re-run了一下😂

**Comment by ReaJason** [comment]
> > > > > > 你贴一下你写的cron
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > > > 
> > > > 
> > > > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> > > 
> > > 
> > > 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静
> > 
> > 
> > 好家伙，刚有动静了
> 
> 刚刚是我手动re-run了一下😂

我建议重新fork一下，它可能被你玩坏了🙊

**Comment by ReaJason** [comment]
> > > > > > 你贴一下你写的cron
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > > > 
> > > > 
> > > > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> > > 
> > > 
> > > 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静
> > 
> > 
> > 好家伙，刚有动静了
> 
> 刚刚是我手动re-run了一下😂

那没事了，反正有延迟是真的，其他我就不知道了🙊

**Comment by sw1128** [comment]
> > > > > > > 你贴一下你写的cron
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > > > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > > > > 
> > > > > 
> > > > > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> > > > 
> > > > 
> > > > 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静
> > > 
> > > 
> > > 好家伙，刚有动静了
> > 
> > 
> > 刚刚是我手动re-run了一下😂
> 
> 我建议重新fork一下，它可能被你玩坏了🙊

好吧，我重新fork试一下

**Comment by sw1128** [comment]
> > > > > > > 你贴一下你写的cron
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/65203923/101973482-6fd3f700-3c73-11eb-9a95-7cb494efc30c.png)
> > > > > > 之前是30 2,4,8改成了05 4,8 刚刚12：05的时候也没打
> > > > > 
> > > > > 
> > > > > 突然想起来这个有时候不是准时的，会大概往后推10+分钟
> > > > 
> > > > 
> > > > 今天12：05没有打，cron还是05 4,8，过了20多分钟了也没动静
> > > 
> > > 
> > > 好家伙，刚有动静了
> > 
> > 
> > 刚刚是我手动re-run了一下😂
> 
> 那没事了，反正有延迟是真的，其他我就不知道了🙊

测试了一下，平均延迟在25-30分钟，可以正常使用，谢谢大佬😂
