### ISSUE TITLE
河南师范大学暂无法使用

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/17wanxiaoCheckin-Actions#23]
由于获取数据的接口完全不一样，暂还没适配，有时间会看有没有机会适配一下，或者大家抓包自己修改一下代码也可以

**Comment by Tomatocicier** [comment]
你好大大，我修改了一些不能自己填写的，提示这个是出现什么问题吗


Run python3 17wanxiao.py <<EOF
  File "17wanxiao.py", line 135
    if j['propertyname'] == 'temperature':  # 找到propertyname为temperature的字段
     ^
IndentationError: expected an indented block
Error: Process completed with exit code 1.

**Comment by ReaJason** [comment]
if还要缩到for里面去，主注意对比一下我的README里面写的

**Comment by ReaJason** [comment]
目前已更新获取不到完美校园post数据的学校，欢迎fork帮忙测试，代码稳定性
