### ISSUE TITLE
作者您好 学校要求打开需要是自动定位怎么办

### ISSUE THREAD

**Issue by HuaiHan** [ReaJason/17wanxiaoCheckin-Actions#24]
![image](https://user-images.githubusercontent.com/45888728/102010500-6339c680-3d79-11eb-9f68-4a6d395b5e3f.png)

**Comment by HuaiHan** [comment]
【已经解决】
1.修改17wanxiao.py
2.手机抓包找到这2个字段
"latitude": "*********",
"longitude": "*********",
3.后面的坐标填写到py文件中即可

**Comment by ReaJason** [comment]
> 【已经解决】
> 1.修改17wanxiao.py
> 2.手机抓包找到这2个字段
> "latitude": "_********", "longitude": "********_",
> 3.后面的坐标填写到py文件中即可

真不错

**Comment by HuaiHan** [comment]
> > [1.] 1.17wanxiao.py]  2.[2]"纬度_********"："，"经度**"："3][2]]。"******_
> 
> 真不错

还要靠你的脚本 大佬

**Comment by TongJiaqi0123** [comment]
这个可以多人用么，抓包之后是填写固定值么

**Comment by ReaJason** [comment]
> 这个可以多人用么，抓包之后是填写固定值么

可以，填写固定值，不填写的话打卡会打不上去

**Comment by HuaiHan** [comment]
> 这个可以多人用么，抓包之后是填写固定值么


实测可以 我们学校只要看你是自动定位就行了其他不管
