### ISSUE TITLE
昨天一切正常，今天只进行了健康打卡，校内打卡没用

### ISSUE THREAD

**Issue by sw1128** [ReaJason/17wanxiaoCheckin-Actions#25]
室友的两种打卡都正常，作者知道哪里出了问题吗

**Comment by ReaJason** [comment]
我写了这个判断时间的函数，只有上午才会上午的校内打卡，你自己调调
```
def get_ap():
    now_time = datetime.datetime.now() + datetime.timedelta(hours=8)
    am = 0 <= now_time.hour < 12
    pm = 12 <= now_time.hour < 17
    ev = 17 <= now_time.hour <= 23
    return [am, pm, ev]
```

**Comment by sw1128** [comment]
> 我写了这个判断时间的函数，只有上午才会上午的校内打卡，你自己调调
> 
> ```
> def get_ap():
>     now_time = datetime.datetime.now() + datetime.timedelta(hours=8)
>     am = 0 <= now_time.hour < 12
>     pm = 12 <= now_time.hour < 17
>     ev = 17 <= now_time.hour <= 23
>     return [am, pm, ev]
> ```

改成了
am = 0 <= now_time.hour < 12
pm = 12 <= now_time.hour <= 23
return [am, pm]
昨天还没问题，今天手动run不管啥时候也都不执行校内打卡，但是Secret放室友的信息就可以，难道是我这个号出问题了（捂脸

**Comment by ReaJason** [comment]
> > 我写了这个判断时间的函数，只有上午才会上午的校内打卡，你自己调调
> > ```
> > def get_ap():
> >     now_time = datetime.datetime.now() + datetime.timedelta(hours=8)
> >     am = 0 <= now_time.hour < 12
> >     pm = 12 <= now_time.hour < 17
> >     ev = 17 <= now_time.hour <= 23
> >     return [am, pm, ev]
> > ```
> 
> 改成了
> am = 0 <= now_time.hour < 12
> pm = 12 <= now_time.hour <= 23
> return [am, pm]
> 昨天还没问题，今天手动run不管啥时候也都不执行校内打卡，但是Secret放室友的信息就可以，难道是我这个号出问题了（捂脸

这个就不是很清楚了

**Comment by ReaJason** [comment]
可以试着调试一下打开这个print，看获取到了校内打卡的和手机里面的是否一致
```
# 获取校内打卡
id_list = get_id_list(token, custom_id)
print(id_list)
if not id_list:
    return check_dict_list
```

**Comment by sw1128** [comment]
> 可以试着调试一下打开这个print，看获取到了校内打卡的和手机里面的是否一致
> 
> ```
> # 获取校内打卡
> id_list = get_id_list(token, custom_id)
> print(id_list)
> if not id_list:
>     return check_dict_list
> ```

print(id_list)返回的None

**Comment by ReaJason** [comment]
那你试试之前我写的另外一个获取Id的接口，改成这样，再看看
‘’‘
id_list = get_id_list_v1(token)
’‘’

**Comment by sw1128** [comment]
> 那你试试之前我写的另外一个获取Id的接口，改成这样，再看看
> 
> ```
> id_list = get_id_list_v1(token)
> ```

这个接口可以了，下午还有一次校内打卡，到时候来反馈

**Comment by sw1128** [comment]
> 那你试试之前我写的另外一个获取Id的接口，改成这样，再看看
> 
> ```
> id_list = get_id_list_v1(token)
> ```

用这个接口校内正常打卡，没问题了

**Comment by ReaJason** [comment]
> > 那你试试之前我写的另外一个获取Id的接口，改成这样，再看看
> > ```
> > id_list = get_id_list_v1(token)
> > ```
> 
> 用这个接口校内正常打卡，没问题了

好的
