### ISSUE TITLE
同学的都正常，只有我的提示参数不合法QAQ

### ISSUE THREAD

**Issue by Soniceso** [ReaJason/17wanxiaoCheckin-Actions#26]
{'msg': '参数不合法', 'code': '10002', 'data': 'areaStr can not be null'}

**Comment by Soniceso** [comment]
之前貌似用抓包的方法试过一次没成功，然后号就变成这样了，应该是它获取不到我新的信息了，用的还是抓包填错的信息，然后同学的号没抓过包就一切正常。。

**Comment by Soniceso** [comment]
解决了，是校外打卡没有填写，但还是有点奇怪明明校内有信息为什么校外获取失败会导致校内的也获取不到。。。

**Comment by ReaJason** [comment]
> 解决了，是校外打卡没有填写，但还是有点奇怪明明校内有信息为什么校外获取失败会导致校内的也获取不到。。。

这我代码设计上的问题，因为校内打卡地址信息的接口获取不到，所以使用的校外打卡的地址来打校内打卡的
