### ISSUE TITLE
我们打卡有些字段名不一样,需要修改什么吗

### ISSUE THREAD

**Issue by 2218675712** [ReaJason/17wanxiaoCheckin-Actions#3]
{
    "businessType": "epmpics",
    "method": "submitUpInfo",
    "jsonData": {
        "deptStr": {
            "deptid": "XXX",
            "text": "XXX"
        },
        "areaStr": "{\"streetNumber\":\"\",\"street\":\"XXX\",\"district\":\"XXX\",\"city\":\"XXX\",\"province\":\"XXX\",\"town\":\"\",\"pois\":\"XXX\",\"lng\":XXX,\"lat\":XXX,\"address\":\"XXX\",\"text\":\"XXX\",\"code\":\"\"}",
        "reportdate": 1595728814778,
        "customerid": "798",
        "deptid": "XXX",
        "source": "app",
        "templateid": "pneumonia",
        "stuNo": "XXX",
        "username": "XXX",
        "phonenum": "",
        "userid": "XXX",
        "updatainfo": [
            {
                "propertyname": "temperature",
                "value": "36.5"
            },
            {
                "propertyname": "symptom",
                "value": "无症状"
            },
            {
                "propertyname": "isConfirmed",
                "value": "否"
            },
            {
                "propertyname": "isdefinde",
                "value": "否.未隔离"
            },
            {
                "propertyname": "isGoWarningAdress",
                "value": "否"
            },
            {
                "propertyname": "isTouch",
                "value": "否"
            },
            {
                "propertyname": "isTransitArea",
                "value": "否"
            },
            {
                "propertyname": "isTransitProvince",
                "value": "否"
            },
            {
                "propertyname": "isFFHasSymptom",
                "value": "没有"
            },
            {
                "propertyname": "jingwai0511",
                "value": "否"
            },
            {
                "propertyname": "tjjw0511",
                "value": "否"
            },
            {
                "propertyname": "bodyzk",
                "value": "是"
            },
            {
                "propertyname": "cxjh",
                "value": "否"
            },
            {
                "propertyname": "isleaveaddress",
                "value": "是"
            },
            {
                "propertyname": "isAlreadyInSchool",
                "value": "没有"
            },
            {
                "propertyname": "hsjc0511",
                "value": "否"
            },
            {
                "propertyname": "emergencyContact",
                "value": "XXX"
            },
            {
                "propertyname": "mergencyPeoplePhone",
                "value": "XXX"
            },
            {
                "propertyname": "assistRemark",
                "value": ""
            },
            {
                "propertyname": "fhhb",
                "value": "否"
            },
            {
                "propertyname": "gyfh",
                "value": "否"
            },
            {
                "propertyname": "ishborwh",
                "value": "否"
            },
            {
                "propertyname": "istouchcb",
                "value": "否"
            }
        ],
        "gpsType": 1
    }
}

**Comment by ReaJason** [comment]
你需要修改四个地方：
1、py文件的jsons的所有代码，设置成你抓包的这个
2、根据你抓包的这个，需要填写的，在py文件最开始使用input进行输入
3、设置run.yml，最后面的输入字段，你这个需要添加一些（需要和py文件的input顺序一致，因为是一行一行input进去的）
4、设置secrets，需要设置多少就设置多少

建议：你可以看到你这个抓包的gpsType是1证明是使用了自动定位的，所以上面的字段areStr字段就多了很多，我建议像我那样，你gpsType设置0，上面地址就只需要两个参数了

**Comment by 2218675712** [comment]
了解了
更改了数组的内容为自己填写的字段,就成功了,
谢谢
