### ISSUE TITLE
报StuNo can not be null 错误

### ISSUE THREAD

**Issue by dll233** [ReaJason/17wanxiaoCheckin-Actions#4]
shell: /bin/bash -e {0}
{
    "code": "10002",
    "data": "StuNo can not be null",
    "msg": "参数不合法"
}
Something Wrong

**Comment by ReaJason** [comment]
请问你的StuNo的secrets字段设置了没有

**Comment by dll233** [comment]
您好，首先感谢您的回复，字段设置无误，已经重试多次，仍旧报相同错误；在文件中直接修改字段"xxxxxxx"（写死变量名）依旧无法解决，期待您的回复

**Comment by dll233** [comment]
直接写死变量名报错如下：
Run python3 17wanxiao.py <<EOF
  python3 17wanxiao.py <<EOF
  ***
  ***
  
  ***
  ***
  
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  EOF
  shell: /bin/bash -e {0}
{
    "code": "10007",
    "data": "您的信息尚未在系统名单中，请再次核实。",
    "msg": "业务异常"
}
Something Wrong

**Comment by ReaJason** [comment]
1、出现"您的信息尚未在系统名单中"，可能就是出现的信息纰漏，如果无误，可以看看自己抓包的json数据和我py文件中的json格式的数据有没有出入，据我所知好像每个学校的打卡信息好像不是特别一样。
2、Something Wrong按我写的逻辑应该是消息没发送出去，请问srckey的字段设置了没有。
3、由于字段特别多，只能通过secrets字段来保护自己的信息，还是有点麻烦，程序很简单基本不会出啥问题。

**Comment by dll233** [comment]
感谢您的回复！
1.我再全部充填一下secret吧，然后我再核对一下json数据问题（似乎确实不是所有学校都一样）。
2.确实没有收到消息，但srckey设置了。
3.我想向您请教：设置secret时 以一个换行结尾是否会导致错误？我习惯性在<value> 后多打了回车，我不知道这是否会与我的报错有关。
4.再次感谢您的回复！期待您的解答！：）

**Comment by dll233** [comment]
抱歉刚刚遗漏了一点，下附补充说明
补充说明：我在使用action时，未按照修改md文件自动触发运行，而是手动添加运行，请问这是否与报错有关？

**Comment by ReaJason** [comment]
好兄弟，我刚试了下在secret字段值最后打了一个空格，发现也出现了错误，这个空格会赋给下一个字段的值所以就是null了，你可以看我刚测试的action，你重新设置一下
![image](https://user-images.githubusercontent.com/48389642/88478339-2875f400-cf7a-11ea-923c-76c8f0789240.png)

**Comment by dll233** [comment]
好兄弟，似乎不可以QAQ，按照我的报错学号不能为空 前一个参数应为CODE，重新修改了也不行，甚至用了和您实例中一样的也不行

**Comment by ReaJason** [comment]
都重新设置一下，可能前面的还有回车，这感觉也没其他办法了.....😂, 我代码里的那串json和你的不一样的话，就设成和你一样的

**Comment by dll233** [comment]
您好，我已完成全部secret的修改，现在可以正常推送。但是仍然报错：信息不在名单内
![image](https://user-images.githubusercontent.com/49135636/88479605-edc48980-cf82-11ea-8233-2245740e4e32.png)
我们抓包的数据显示code字段为空？
![image](https://user-images.githubusercontent.com/49135636/88479629-23697280-cf83-11ea-8631-97478fe62cdd.png)
请问该如何填写secret？
谢谢您的回复！

**Comment by ReaJason** [comment]
code字段没有的话，它其实是本地邮编，你可以在百度上获取一下你填的地址的邮编，填上去

**Comment by dll233** [comment]
您好！试过了本地邮编 学校邮编 还有您例子里的邮编，都不行QAQ

**Comment by ReaJason** [comment]
如果信任的话，可以加一下我qq1587047405，我帮你找找问题

**Comment by dll233** [comment]
您好，抓包内容如下：已进行脱敏处理
https://paste.ubuntu.com/p/NTGmqM3Yz6/

**Comment by 571640898** [comment]
我也遇到类似情况，code10007;改了下py里的customerid，改成了自己抓包出来的值，可以正常打卡了
