### ISSUE TITLE
腾讯云函数版

### ISSUE THREAD

**Issue by ReaJason** [ReaJason/17wanxiaoCheckin-Actions#51]
参考教程：https://reajason.top/2021/01/17/17wanxiaoCheckin-SCF/](https://reajason.top/2021/01/17/17wanxiaoCheckin-SCF/)

**Comment by asayake777** [comment]
所以是github的原因吗，我刚才还又fork了准备重试...QAQ

**Comment by n1ght2** [comment]
SC推送好像失效了

**Comment by ReaJason** [comment]
> SC推送好像失效了

好像有点问题，不过现在还好，https://weibo.com/1088413295/JDqyatOic?from=page_1005051088413295_profile&wvr=6&mod=weibotime

**Comment by n1ght2** [comment]
> > SC推送好像失效了
> 
> 好像有点问题，不过现在还好，https://weibo.com/1088413295/JDqyatOic?from=page_1005051088413295_profile&wvr=6&mod=weibotime

现在确实好了~
