### ISSUE TITLE
code10007

### ISSUE THREAD

**Issue by LMDHCN** [ReaJason/17wanxiaoCheckin-Actions#8]
data：您的信息尚未在系统名单中，请再次核实。
我觉得是我紧急联系人的问题，但我抓包只有紧急电话，并且此电话就是我本人电话。
紧急联系人那里我填的“紧急人”（尬笑），大佬来看看问题在哪，我去试试改成其他名字

**Comment by LMDHCN** [comment]
我信息没删，求大佬看看我fork的问题出在哪，秋梨膏！

**Comment by By-awen** [comment]
我也是 响应数据：
    { msg: "业务异常", code: "10007", data: "您的信息尚未在系统名单中，请再次核实。"}

**Comment by LMDHCN** [comment]
我想我明白了，咱们两所学校的要求内容不一样，我再去试试，这回应该没问题了

**Comment by By-awen** [comment]
我弄好了 是不一样的&nbsp; &nbsp;根据抓包内容改一下就行了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LMDHCN"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 上午7:09
收件人: "ReaJason/17wanxiaoCheckin-Actions"<17wanxiaoCheckin-Actions@noreply.github.com&gt;; 
抄送: "             "<329911860@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ReaJason/17wanxiaoCheckin-Actions] code10007 (#8)





 
我想我明白了，咱们两所学校的要求内容不一样，我再去试试，这回应该没问题了
