### ISSUE TITLE
运行后HealthCheckin中的报错情况

### ISSUE THREAD

**Issue by adwhite373** [ReaJason/17wanxiaoCheckin-Actions#9]
"code"：“10007"，
“data"：“您的信息尚未在系统名单中，请再次核实。”，
“msg”：“业务异常”

**Comment by ReaJason** [comment]
json字段的问题，检查一下Secret信息是否填写正确了

**Comment by ReaJason** [comment]
如果自己的json字段和我的有出入的话，要去修改一下代码
